name: 'advent_of_code_2023'
version: '1.0.0'
config-version: 2

profile: default

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  advent_of_code_2023:
    # Config indicated by + and applies to all files under models/example/
    +materialized: view
